interval: 3 # Interval between pollings
loglevel: 5 # 1-5
# Prometheus metrics are exposed at http://exporter_address/metrics
exporter_address: :8081

## logstash sink. Lug will send all logs to this address
# logstash_address: logstash.metrics.foobar.com:1234

# Address where JSON API will be served
json_api:
    address: :7001
    # certfile: "/foobar/tls.cer"
    # keyfile: "/foobar/foobar.com.key"
    # username: "example"
    # password: "example"

repos:
    - type: rsync
      source: rsync://rsync.chiark.greenend.org.uk/ftp/users/sgtatham/putty-website-mirror/
      interval: 6
      path: /tmp/putty
      name: putty
    - type: external
      name: external_worker
      customized_key: any_value_parsed_by_external_program
