interval: 3 # Interval between pollings
loglevel: 5 # 1-5
# Prometheus metrics are exposed at http://exporter_address/metrics
exporter_address: :8081

#logstash:
#   address: listener.logz.io:5050 # logstash sink. Lug will send all logs to this address
#   additional_fields:
#       token: "" # Additional fields sent to logstash server

# Address where JSON API will be served
json_api:
    address: :7001

repos:
    - type: rsync
      source: rsync://rsync.chiark.greenend.org.uk/ftp/users/sgtatham/putty-website-mirror/
      interval: 6
      path: /tmp/putty
      name: putty
    - type: external
      name: ubuntu
      proxy_to: http://ftp.sjtu.edu.cn/ubuntu/
