interval: 3 # Interval between pollings
loglevel: 5 # 1-5
exporter_address: :8081
repos:
    - type: rsync
      source: rsync://rsync.chiark.greenend.org.uk/ftp/users/sgtatham/putty-website-mirror/
      interval: 6
      path: /tmp/putty
      name: putty
    - type: external
      name: external_worker
      customized_key: any_value_parsed_by_external_program